**DIFFERENT WAYS TO GET WORD EMBEDDING**
1. Use Pretrained model - Word2Vec, Glove
2. Train our own Embedding layer using Word2Vec library
3. Train our own Embedding layer using Keras embedding method

**2. Train our own Embedding layer using Word2Vec library**

In [5]:
tokenized_sentences=[['Hello','Mahesh','Welcome','to','word','Embedding'],
                     ['Hope','you','are','doing','well'],
                     ['Butter', 'is', 'good','for', 'health'],
                     ['Today','is','hot','weather']]

In [6]:
from gensim.models import Word2Vec

In [7]:
model= Word2Vec(sentences=tokenized_sentences,min_count=1) #Taking all the words which has occured only once

In [8]:
print(model)

Word2Vec(vocab=19, size=100, alpha=0.025)


In [10]:
words = list(model.wv.vocab)
words

#words=list(model.wv.index_to_key) In newer version of gensim, vocab is not there


['Hello',
 'Mahesh',
 'Welcome',
 'to',
 'word',
 'Embedding',
 'Hope',
 'you',
 'are',
 'doing',
 'well',
 'Butter',
 'is',
 'good',
 'for',
 'health',
 'Today',
 'hot',
 'weather']

In [11]:
#I want to see the vector of training
print(model['Welcome']) #The word training has been rated on 100 different features
#Encoded value for the word "Welcome"

[ 3.7650601e-03 -1.2179224e-03 -4.2425847e-04 -8.9386239e-04
  2.1250078e-03  3.8709927e-03  2.7244866e-03 -2.5924814e-05
  6.1725947e-04  3.1192394e-03  4.6339417e-03 -3.8614331e-03
  2.5257054e-03  4.0875631e-03  1.4241303e-03  2.0040891e-03
 -1.2782528e-03 -4.3493896e-03  3.5739685e-03  1.5832009e-04
 -3.1627368e-03 -7.0243684e-04 -4.1268443e-04  2.2434241e-03
 -4.3932437e-03  3.9895754e-03 -1.9408502e-03  1.0702274e-03
 -2.5505740e-03 -9.4581617e-04  1.6238312e-03  1.1948169e-03
 -1.1103308e-03  2.7468204e-03 -4.8664892e-03 -7.2940061e-04
  1.5076114e-03  2.6693153e-03 -3.9647511e-04  9.2143040e-05
 -2.3899819e-03 -2.4591095e-03 -2.4214603e-06  1.1295952e-03
 -1.6421850e-03 -3.0808675e-03  4.9064187e-03  1.7273466e-03
 -4.1975162e-04  1.9720905e-03 -2.1403860e-03 -4.1825376e-03
 -3.5133825e-03 -4.0898267e-03  2.9074191e-04 -3.2694489e-03
 -3.1641005e-03  2.0034814e-03 -4.3100727e-06 -4.5858743e-03
 -6.1535969e-04  9.4023708e-04 -4.8876232e-03 -1.8397727e-03
  1.5647954e-03 -4.64353

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


In [ ]:
## AS THE WORD "World" is not there in our vocabulary, Thus it will show error here
print(model['World']) 

In [13]:
model.most_similar('Hello') #the vector of Hello is compared with all other words

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  """Entry point for launching an IPython kernel.


[('you', 0.12667392194271088),
 ('is', 0.10743431746959686),
 ('for', 0.08030496537685394),
 ('doing', 0.07783336192369461),
 ('Today', 0.06990745663642883),
 ('well', 0.05721601843833923),
 ('health', 0.0514802522957325),
 ('Mahesh', 0.051442719995975494),
 ('Welcome', 0.020477555692195892),
 ('Embedding', 0.005391038954257965)]

In [ ]:
model.most_similar('Apple') 

### ** TAKE AWAY FROM ABOVE. Here there is BIG LIMITATION** When we train our model by our own from scratch, the Model is not able to identify any new word like as mentioned "Apple". Because it is not there in our mentioned library.  Thus, it is the disadvantage of when we train our own network


**3. Train our own Embedding layer using Keras embedding method**

In [14]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [17]:
#Define your own documents
sentences = ['This is a great product', 
             'Mobile is awesome machine',
             'It is beyond expectation',
             'Battery is insane',
             'Display is not good']

In [16]:
sent_labels = array([1,1,1,0,0])  # Positive sentences are assigned:1, and Negative are assigned:0

In [18]:
vocab_size = 50 #Is it dimension?
encoded_sent = [one_hot(i,vocab_size)for i in sentences]
encoded_sent

[[29, 35, 15, 36, 40],
 [32, 35, 31, 20],
 [26, 35, 23, 47],
 [20, 35, 14],
 [19, 35, 22, 44]]

In [21]:
# Now I want to train my Neural Network, Thus, the size of the vector should be same. THUS APPLYING PADDING
# Padding aage add kardega, "padding=post" doge toh piche zeros add kardega
padded_sent = pad_sequences(encoded_sent,maxlen = 6,padding='pre')
print(padded_sent)

[[ 0 29 35 15 36 40]
 [ 0  0 32 35 31 20]
 [ 0  0 26 35 23 47]
 [ 0  0  0 20 35 14]
 [ 0  0 19 35 22 44]]


In [22]:
mymodel = Sequential()
mymodel.add(Embedding(vocab_size,8,input_length = 6))
mymodel.add(Flatten())
mymodel.add(Dense(1,activation = 'sigmoid')) #Because target is categorical in nature

In [23]:
mymodel.compile(optimizer='adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [24]:
mymodel.fit(padded_sent,sent_labels,epochs = 33)

Epoch 1/33
1/1 [==============================] - 14s 14s/step - loss: 0.7052 - accuracy: 0.4000
Epoch 2/33
1/1 [==============================] - 0s 5ms/step - loss: 0.7022 - accuracy: 0.4000
Epoch 3/33
1/1 [==============================] - 0s 6ms/step - loss: 0.6992 - accuracy: 0.4000
Epoch 4/33
1/1 [==============================] - 0s 9ms/step - loss: 0.6961 - accuracy: 0.4000
Epoch 5/33
1/1 [==============================] - 0s 6ms/step - loss: 0.6932 - accuracy: 0.4000
Epoch 6/33
1/1 [==============================] - 0s 6ms/step - loss: 0.6902 - accuracy: 0.4000
Epoch 7/33
1/1 [==============================] - 0s 7ms/step - loss: 0.6872 - accuracy: 0.4000
Epoch 8/33
1/1 [==============================] - 0s 8ms/step - loss: 0.6843 - accuracy: 0.4000
Epoch 9/33
1/1 [==============================] - 0s 7ms/step - loss: 0.6813 - accuracy: 0.4000
Epoch 10/33
1/1 [==============================] - 0s 6ms/step - loss: 0.6784 - accuracy: 0.6000
Epoch 11/33
1/1 [=====================

**EVALUATION:- TEST ACCURACY**

In [27]:
mymodel.evaluate(padded_sent,sent_labels,verbose = 1)

1/1 [==============================] - 0s 444ms/step - loss: 0.6079 - accuracy: 1.0000


[0.6079109311103821, 1.0]

In [28]:
model_loss,model_accuracy = mymodel.evaluate(padded_sent,sent_labels,verbose = 1)
print('Accuracy : %f' %(model_accuracy*100))

1/1 [==============================] - 0s 18ms/step - loss: 0.6079 - accuracy: 1.0000
Accuracy : 100.000000


**THE PREDICTION**

In [41]:
sent_for_pred = ['Mobile is awesome machine',
                 'Battery is insane']

In [42]:
vocab_size = 50 #Is it dimension?
encoded = [one_hot(i,vocab_size)for i in sent_for_pred]
encoded

[[32, 35, 31, 20], [20, 35, 14]]

In [43]:
padded_sent = pad_sequences(encoded,maxlen = 6,padding='pre')
print(padded_sent)

[[ 0  0 32 35 31 20]
 [ 0  0  0 20 35 14]]


In [44]:
mymodel.predict_classes(padded_sent)

/usr/local/lib/python3.7/dist-packages/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[1],
       [0]], dtype=int32)

**TAKE AWAY FROM ABOVE CODE**
Here vocabulary is so less, that predictions will not be upto the mark., thus we NEED TO IMPORT VOCABULARY PACKAGES FROM INTERNET

**1. USE PRETRAINNED WORD2VEC MODELS**

In [45]:
from gensim.models import Word2Vec, KeyedVectors

In [ ]:
# DONWLOAD PRETRAINNED VOCABULARY
pretrained_model = KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin',binary = True)

In [ ]:
pretrained_model.most_similar('data')
print(result)